name: Build source code
on: [push]

jobs:
  build:
    strategy:
      matrix:
        image: ["centos:8"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
        # options: -v ${{ github.workspace }}:/root/src/ -w /root/src/
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Ls
        run: ls -la
